;this file for FamiTone2 library generated by text2data tool

TestMusic3_music_data:
	.byte 8
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256
	.word @song2ch0,@song2ch1,@song2ch2,@song2ch3,@song2ch4,307,256
	.word @song3ch0,@song3ch1,@song3ch2,@song3ch3,@song3ch4,307,256
	.word @song4ch0,@song4ch1,@song4ch2,@song4ch3,@song4ch4,307,256
	.word @song5ch0,@song5ch1,@song5ch2,@song5ch3,@song5ch4,307,256
	.word @song6ch0,@song6ch1,@song6ch2,@song6ch3,@song6ch4,307,256
	.word @song7ch0,@song7ch1,@song7ch2,@song7ch3,@song7ch4,307,256

@instruments:
	.byte $b0 ;instrument $00
	.word @env10,@env19,@env0
	.byte $00
	.byte $b0 ;instrument $02
	.word @env13,@env0,@env13
	.byte $00
	.byte $70 ;instrument $03
	.word @env14,@env0,@env20
	.byte $00
	.byte $70 ;instrument $04
	.word @env15,@env0,@env20
	.byte $00
	.byte $30 ;instrument $08
	.word @env6,@env17,@env0
	.byte $00
	.byte $30 ;instrument $09
	.word @env7,@env18,@env0
	.byte $00
	.byte $30 ;instrument $0a
	.word @env5,@env16,@env0
	.byte $00
	.byte $b0 ;instrument $17
	.word @env1,@env0,@env20
	.byte $00
	.byte $70 ;instrument $18
	.word @env2,@env0,@env20
	.byte $00
	.byte $70 ;instrument $1a
	.word @env11,@env0,@env20
	.byte $00
	.byte $70 ;instrument $1b
	.word @env12,@env0,@env20
	.byte $00
	.byte $b0 ;instrument $1c
	.word @env3,@env0,@env20
	.byte $00
	.byte $70 ;instrument $20
	.word @env4,@env0,@env20
	.byte $00
	.byte $70 ;instrument $22
	.word @env2,@env0,@env21
	.byte $00
	.byte $b0 ;instrument $30
	.word @env8,@env0,@env20
	.byte $00
	.byte $70 ;instrument $31
	.word @env9,@env0,@env22
	.byte $00
	.byte $30 ;instrument $33
	.word @env0,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c2,$c3,$c5,$c6,$c7,$c8,$05,$c7,$c3,$00,$08
@env2:
	.byte $c8,$c7,$c6,$c5,$c4,$c3,$c2,$c1,$c4,$c4,$c3,$c3,$c2,$c1,$02,$c3
	.byte $c2,$c2,$c1,$04,$c2,$c1,$0c,$c2,$c1,$c0,$00,$19
@env3:
	.byte $c2,$c3,$c3,$c4,$c5,$c6,$c7,$c7,$c6,$c5,$c5,$c4,$00,$0b
@env4:
	.byte $c5,$ca,$c9,$c8,$02,$c7,$c7,$c6,$00,$07
@env5:
	.byte $ce,$c7,$c3,$c4,$c2,$c1,$05,$c0,$00,$07
@env6:
	.byte $c6,$c2,$c2,$c1,$c0,$00,$04
@env7:
	.byte $ca,$ca,$c7,$c6,$03,$c5,$00,$05
@env8:
	.byte $c5,$c7,$c7,$c6,$02,$c5,$02,$c4,$02,$c5,$c5,$c4,$c4,$c3,$c3,$c4
	.byte $c4,$c3,$c3,$c4,$c4,$00,$09
@env9:
	.byte $c5,$c7,$c7,$c6,$02,$c5,$02,$c4,$02,$c5,$c5,$c4,$c4,$c3,$c3,$c4
	.byte $c1,$00,$10
@env10:
	.byte $ca,$c9,$c8,$c7,$c7,$c6,$c0,$00,$06
@env11:
	.byte $c6,$c6,$c5,$02,$c4,$c5,$c5,$c4,$c5,$04,$c4,$c4,$c3,$00,$0c
@env12:
	.byte $c7,$c7,$c6,$03,$c5,$07,$c4,$00,$06
@env13:
	.byte $c3,$00,$00
@env14:
	.byte $c8,$c7,$c6,$c5,$c4,$c3,$c2,$0b,$c1,$15,$c0,$00,$0a
@env15:
	.byte $c6,$c6,$c5,$04,$c4,$04,$c3,$c3,$c3,$00,$08
@env16:
	.byte $c1,$c9,$cb,$cc,$cb,$cc,$cd,$cd,$cf,$00,$07
@env17:
	.byte $ca,$cb,$ce,$00,$02
@env18:
	.byte $cd,$ce,$05,$cf,$cf,$ce,$ce,$00,$03
@env19:
	.byte $be,$bf,$c0,$00,$02
@env20:
	.byte $c1,$23,$c2,$c4,$c4,$c2,$c2,$c1,$bf,$bf,$bd,$bd,$bf,$c1,$c1,$00
	.byte $02
@env21:
	.byte $bc,$bf,$c2,$c0,$05,$bf,$be,$bf,$c0,$c1,$c2,$c1,$c0,$00,$05
@env22:
	.byte $c1,$11,$c2,$c4,$c4,$c2,$c2,$c1,$bf,$bf,$bd,$bd,$bf,$c1,$c1,$00
	.byte $02


@song0ch0:
	.byte $fb,$05
@song0ch0loop:
@ref0:
	.byte $9c,$3d,$00,$39,$33,$00,$32,$39,$00,$3d,$00,$39,$33,$00,$32,$39
	.byte $00
@ref1:
	.byte $3d,$00,$39,$33,$00,$32,$39,$00,$3d,$00,$91
@ref2:
	.byte $3d,$00,$39,$33,$00,$32,$39,$00,$3d,$00,$39,$33,$00,$32,$39,$00
	.byte $ff,$0b
	.word @ref1
@ref4:
	.byte $9e,$54,$89,$55,$58,$83,$5b,$00,$5b,$00,$5b,$00,$58,$55,$00
@ref5:
	.byte $59,$00,$59,$00,$54,$83,$01,$50,$85,$00,$8f
@ref6:
	.byte $85,$4a,$83,$50,$83,$4b,$50,$85,$4a,$83,$54,$83,$50,$83
@ref7:
	.byte $54,$89,$00,$83,$5f,$5a,$54,$89,$00,$89
@ref8:
	.byte $54,$83,$51,$4d,$00,$5a,$83,$00,$54,$85,$00,$50,$55,$00,$55,$00
@ref9:
	.byte $59,$00,$59,$00,$54,$83,$01,$50,$85,$00,$89,$50,$83
@ref10:
	.byte $54,$89,$00,$83,$4a,$83,$50,$89,$51,$4a,$50,$83
@ref11:
	.byte $9c,$3d,$00,$39,$33,$00,$32,$39,$00,$3d,$00,$80,$54,$89,$54,$83
	.byte $ff,$0e
	.word @ref4
	.byte $ff,$0b
	.word @ref5
	.byte $ff,$0e
	.word @ref6
	.byte $ff,$0a
	.word @ref7
	.byte $ff,$10
	.word @ref8
	.byte $ff,$0b
	.word @ref5
	.byte $ff,$0e
	.word @ref6
@ref19:
	.byte $54,$89,$00,$83,$5f,$5a,$54,$83,$80,$54,$89,$54,$83
@ref20:
	.byte $54,$83,$9e,$5f,$5a,$5e,$83,$5b,$5e,$01,$63,$00,$5a,$5e,$83,$80
	.byte $54,$83
@ref21:
	.byte $58,$83,$9e,$63,$5e,$5b,$58,$51,$00,$80,$58,$83,$9e,$51,$54,$80
	.byte $58,$83,$9e,$51,$54
@ref22:
	.byte $80,$50,$83,$9e,$51,$54,$5a,$83,$51,$5a,$01,$5f,$00,$5e,$5a,$83
	.byte $80,$50,$83
@ref23:
	.byte $4a,$83,$9e,$63,$5e,$5b,$50,$55,$00,$80,$4a,$83,$9e,$51,$54,$80
	.byte $4a,$83,$9e,$51,$54
@ref24:
	.byte $80,$4c,$83,$9e,$5f,$5a,$5e,$83,$5b,$5e,$01,$63,$00,$5a,$5e,$83
	.byte $80,$4c,$83
@ref25:
	.byte $4c,$83,$9e,$59,$54,$59,$54,$4d,$00,$80,$4c,$83,$9e,$58,$83,$80
	.byte $4c,$83,$9e,$4c,$83
@ref26:
	.byte $80,$4a,$83,$9e,$4b,$50,$83,$4a,$80,$4a,$83,$4a,$83,$9e,$51,$54
	.byte $83,$50,$80,$4a,$83
@ref27:
	.byte $4a,$83,$9e,$4b,$50,$83,$58,$80,$4a,$83,$4a,$83,$9c,$4b,$46,$41
	.byte $32,$38,$83
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref28:
	.byte $9c,$33,$00,$87,$01,$2f,$00,$33,$00,$8b,$2f,$00
@ref29:
	.byte $33,$00,$8b,$2f,$00,$33,$00,$91
@ref30:
	.byte $33,$00,$87,$01,$2f,$00,$33,$00,$8b,$2f,$00
	.byte $ff,$08
	.word @ref29
@ref32:
	.byte $92,$25,$28,$2b,$2e,$33,$2e,$2b,$28,$25,$28,$2b,$2e,$33,$2e,$2b
	.byte $28
@ref33:
	.byte $21,$24,$29,$2a,$2f,$2a,$29,$24,$21,$24,$29,$2a,$2f,$2a,$29,$24
@ref34:
	.byte $21,$24,$29,$2a,$2f,$2a,$29,$24,$21,$24,$29,$2a,$2f,$2a,$29,$20
@ref35:
	.byte $25,$28,$2b,$2e,$33,$2e,$2b,$28,$25,$28,$2b,$2e,$33,$2e,$2b,$28
@ref36:
	.byte $1d,$20,$25,$28,$2b,$28,$25,$20,$1d,$20,$25,$28,$2b,$28,$25,$1c
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
@ref39:
	.byte $9c,$33,$00,$8b,$2f,$00,$33,$00,$80,$4a,$89,$4a,$83
	.byte $ff,$10
	.word @ref32
	.byte $ff,$10
	.word @ref33
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
	.byte $ff,$10
	.word @ref36
	.byte $ff,$10
	.word @ref34
	.byte $ff,$10
	.word @ref35
@ref47:
	.byte $9e,$4a,$89,$00,$83,$55,$50,$4a,$83,$80,$4a,$89,$4a,$83
@ref48:
	.byte $4c,$83,$94,$25,$1c,$25,$1c,$25,$1c,$85,$25,$1c,$25,$1c,$80,$4c
	.byte $83
@ref49:
	.byte $50,$83,$94,$29,$20,$29,$20,$29,$20,$80,$50,$83,$94,$29,$20,$80
	.byte $50,$83,$94,$29,$20
@ref50:
	.byte $80,$5a,$83,$94,$2b,$20,$2b,$20,$2b,$20,$85,$2b,$20,$2b,$20,$80
	.byte $5a,$83
@ref51:
	.byte $54,$83,$94,$25,$1a,$25,$1a,$25,$1a,$80,$54,$83,$94,$25,$1a,$80
	.byte $54,$83,$94,$25,$1a
@ref52:
	.byte $80,$54,$83,$94,$25,$1c,$25,$1c,$25,$1c,$85,$25,$1c,$25,$1c,$80
	.byte $54,$83
@ref53:
	.byte $58,$83,$94,$29,$1c,$29,$1c,$29,$1c,$80,$58,$83,$94,$29,$1c,$80
	.byte $58,$83,$94,$29,$1c
@ref54:
	.byte $80,$58,$83,$94,$21,$1a,$21,$1a,$80,$59,$94,$1a,$80,$58,$83,$94
	.byte $21,$1a,$21,$1a,$80,$59,$94,$1a
@ref55:
	.byte $80,$58,$83,$94,$21,$1a,$21,$1a,$80,$59,$94,$1a,$80,$58,$95
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref56:
	.byte $a0,$24,$83,$01,$1b,$01,$1a,$83,$24,$83,$01,$1b,$01,$1a,$83
@ref57:
	.byte $24,$83,$01,$1b,$01,$1a,$83,$24,$83,$01,$21,$01,$22,$83
@ref58:
	.byte $24,$83,$01,$1b,$01,$1a,$83,$24,$83,$01,$1b,$01,$1a,$83
	.byte $ff,$0e
	.word @ref57
@ref60:
	.byte $25,$00,$25,$00,$33,$2e,$83,$2a,$25,$00,$25,$00,$33,$2e,$83,$2a
@ref61:
	.byte $21,$00,$21,$00,$2f,$28,$83,$24,$21,$00,$21,$00,$2f,$28,$83,$24
@ref62:
	.byte $1b,$00,$1b,$00,$29,$24,$83,$20,$1b,$00,$1b,$00,$29,$24,$83,$20
	.byte $ff,$10
	.word @ref60
@ref64:
	.byte $1d,$00,$1d,$00,$2b,$24,$83,$20,$1d,$00,$1d,$00,$2b,$24,$83,$1c
	.byte $ff,$10
	.word @ref61
	.byte $ff,$10
	.word @ref60
@ref67:
	.byte $25,$00,$25,$00,$33,$2e,$83,$2a,$25,$00,$91
	.byte $ff,$10
	.word @ref60
	.byte $ff,$10
	.word @ref61
	.byte $ff,$10
	.word @ref62
	.byte $ff,$10
	.word @ref60
	.byte $ff,$10
	.word @ref64
	.byte $ff,$10
	.word @ref61
	.byte $ff,$10
	.word @ref60
	.byte $ff,$0b
	.word @ref67
@ref76:
	.byte $2e,$83,$46,$01,$2e,$83,$46,$01,$2e,$83,$46,$00,$2f,$00,$2e,$46
	.byte $83
@ref77:
	.byte $20,$83,$38,$01,$20,$83,$38,$01,$20,$83,$38,$00,$21,$00,$20,$38
	.byte $83
@ref78:
	.byte $2a,$83,$42,$01,$2a,$83,$42,$01,$2a,$83,$42,$00,$2b,$00,$2a,$42
	.byte $83
@ref79:
	.byte $24,$83,$3c,$01,$24,$83,$3c,$01,$24,$83,$3c,$00,$25,$00,$24,$3c
	.byte $83
	.byte $ff,$11
	.word @ref76
@ref81:
	.byte $28,$83,$40,$01,$28,$83,$40,$01,$28,$83,$40,$00,$29,$00,$28,$40
	.byte $83
@ref82:
	.byte $1a,$83,$32,$01,$1a,$83,$32,$01,$1a,$83,$32,$00,$1b,$00,$1a,$32
	.byte $83
@ref83:
	.byte $1a,$83,$32,$01,$1a,$83,$32,$01,$1a,$83,$00,$83,$20,$83,$22,$83
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref84:
	.byte $88,$20,$83,$20,$83,$8a,$20,$83,$88,$21,$20,$20,$83,$20,$83,$8a
	.byte $20,$83,$88,$21,$20
@ref85:
	.byte $20,$83,$20,$83,$8a,$20,$83,$88,$21,$20,$8c,$12,$83,$88,$21,$8c
	.byte $12,$83,$88,$20,$8c,$13,$12
	.byte $ff,$10
	.word @ref84
@ref87:
	.byte $20,$83,$20,$83,$8a,$20,$83,$88,$21,$20,$8c,$12,$83,$88,$05,$04
	.byte $8c,$05,$88,$20,$8c,$05,$04
@ref88:
	.byte $88,$18,$83,$19,$18,$8c,$19,$88,$18,$19,$8c,$18,$88,$19,$8c,$18
	.byte $88,$19,$18,$8c,$19,$88,$18,$19,$18
@ref89:
	.byte $18,$83,$19,$18,$8c,$19,$88,$18,$19,$8c,$18,$88,$19,$8c,$18,$88
	.byte $19,$18,$8c,$19,$88,$18,$19,$18
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
@ref95:
	.byte $8c,$12,$83,$88,$21,$8c,$12,$83,$88,$20,$8c,$13,$12,$04,$83,$88
	.byte $19,$18,$8c,$04,$83,$04,$83
	.byte $ff,$10
	.word @ref88
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
	.byte $ff,$10
	.word @ref89
@ref103:
	.byte $8c,$12,$83,$88,$21,$8c,$12,$83,$88,$20,$8c,$13,$12,$12,$89,$04
	.byte $83,$05,$04
@ref104:
	.byte $0b,$88,$16,$17,$8c,$0a,$83,$88,$16,$8c,$0b,$88,$16,$8c,$0b,$88
	.byte $16,$17,$8c,$0a,$83,$88,$16,$8c,$0b,$88,$16
@ref105:
	.byte $8c,$0b,$88,$16,$17,$8c,$0a,$83,$88,$16,$8c,$0b,$88,$1e,$8c,$0a
	.byte $83,$88,$17,$16,$8c,$0a,$83,$8a,$11,$8c,$0a
	.byte $ff,$10
	.word @ref104
	.byte $ff,$10
	.word @ref105
	.byte $ff,$10
	.word @ref104
	.byte $ff,$10
	.word @ref105
	.byte $ff,$10
	.word @ref104
@ref111:
	.byte $8c,$0b,$88,$16,$17,$8c,$0a,$83,$88,$16,$8c,$0b,$88,$1e,$8c,$0a
	.byte $83,$00,$83,$0f,$0e,$0f,$0e
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref112:
	.byte $af
@ref113:
	.byte $af
@ref114:
	.byte $af
@ref115:
	.byte $af
@ref116:
	.byte $af
@ref117:
	.byte $af
@ref118:
	.byte $af
@ref119:
	.byte $af
@ref120:
	.byte $af
@ref121:
	.byte $af
@ref122:
	.byte $af
@ref123:
	.byte $af
@ref124:
	.byte $af
@ref125:
	.byte $af
@ref126:
	.byte $af
@ref127:
	.byte $af
@ref128:
	.byte $af
@ref129:
	.byte $af
@ref130:
	.byte $af
@ref131:
	.byte $af
@ref132:
	.byte $af
@ref133:
	.byte $af
@ref134:
	.byte $af
@ref135:
	.byte $af
@ref136:
	.byte $af
@ref137:
	.byte $af
@ref138:
	.byte $af
@ref139:
	.byte $af
	.byte $fd
	.word @song0ch4loop


@song1ch0:
	.byte $fb,$06
@song1ch0loop:
@ref140:
	.byte $9c,$60,$83,$56,$61,$01,$60,$83,$58,$61,$00,$81
@ref141:
	.byte $61,$49,$51,$57,$61,$00,$89
@ref142:
	.byte $9a,$30,$85,$3a,$85,$30,$85,$3a,$85,$2c,$85,$32,$85,$30,$85,$3a
	.byte $85
@ref143:
	.byte $2c,$85,$32,$85,$30,$85,$3a,$85,$9c,$3f,$01,$49,$01,$41,$3f,$3b
	.byte $00,$81
	.byte $ff,$10
	.word @ref142
@ref145:
	.byte $2c,$85,$36,$85,$26,$85,$36,$85,$9c,$57,$01,$4d,$57,$49,$00,$89
@ref146:
	.byte $90,$58,$85,$58,$85,$58,$85,$58,$85,$5c,$85,$5c,$85,$5c,$85,$5c
	.byte $85
@ref147:
	.byte $9a,$31,$19,$21,$27,$30,$85,$00,$85,$31,$19,$23,$29,$30,$85,$00
	.byte $85
	.byte $ff,$10
	.word @ref146
@ref149:
	.byte $9a,$30,$85,$3a,$85,$30,$85,$3a,$85,$9c,$41,$01,$3b,$3f,$3b,$00
	.byte $89
	.byte $ff,$10
	.word @ref142
	.byte $ff,$11
	.word @ref143
	.byte $ff,$10
	.word @ref142
	.byte $ff,$0f
	.word @ref145
	.byte $ff,$10
	.word @ref146
	.byte $ff,$10
	.word @ref147
	.byte $ff,$10
	.word @ref146
	.byte $ff,$0f
	.word @ref149
@ref158:
	.byte $83,$82,$58,$85,$56,$85,$54,$85,$52,$81
@ref159:
	.byte $83,$4e,$85,$4a,$85,$48,$85,$44,$81
@ref160:
	.byte $01,$41,$45,$49,$4b,$4f,$4d,$4f,$49,$4b,$4f,$53,$55,$59,$57,$58
	.byte $81
@ref161:
	.byte $9c,$3d,$45,$37,$3d,$31,$37,$29,$31,$33,$3b,$29,$33,$23,$29,$1b
	.byte $22,$81
@ref162:
	.byte $01,$82,$41,$45,$49,$4b,$4f,$4d,$4f,$49,$4b,$4f,$53,$55,$59,$57
	.byte $58,$81
@ref163:
	.byte $9c,$41,$49,$3b,$41,$31,$3b,$29,$31,$31,$39,$3f,$49,$3b,$01,$3b
	.byte $00,$81
	.byte $fd
	.word @song1ch0loop

@song1ch1:
@song1ch1loop:
@ref164:
	.byte $9c,$48,$83,$3e,$49,$01,$48,$83,$40,$49,$00,$81
@ref165:
	.byte $49,$31,$39,$3f,$49,$00,$89
@ref166:
	.byte $53,$01,$53,$57,$59,$01,$61,$01,$63,$01,$6b,$01,$60,$89,$00,$81
@ref167:
	.byte $5c,$52,$4a,$52,$63,$01,$58,$52,$48,$52,$61,$01,$57,$01,$61,$01
	.byte $59,$57,$53,$00,$81
	.byte $ff,$10
	.word @ref166
@ref169:
	.byte $61,$5f,$61,$65,$67,$65,$67,$6b,$6f,$01,$65,$6f,$61,$00,$89
@ref170:
	.byte $90,$60,$85,$60,$85,$60,$85,$60,$85,$62,$85,$62,$85,$62,$85,$62
	.byte $85
@ref171:
	.byte $9c,$49,$01,$49,$4d,$51,$49,$57,$01,$53,$01,$53,$57,$59,$53,$61
	.byte $00,$81
	.byte $ff,$10
	.word @ref170
@ref173:
	.byte $9c,$61,$53,$49,$01,$41,$49,$53,$01,$59,$01,$53,$57,$53,$00,$89
	.byte $ff,$10
	.word @ref166
	.byte $ff,$15
	.word @ref167
	.byte $ff,$10
	.word @ref166
	.byte $ff,$0f
	.word @ref169
	.byte $ff,$10
	.word @ref170
	.byte $ff,$11
	.word @ref171
	.byte $ff,$10
	.word @ref170
	.byte $ff,$0f
	.word @ref173
@ref182:
	.byte $8e,$58,$85,$56,$85,$54,$85,$52,$85
@ref183:
	.byte $4e,$85,$4a,$85,$48,$85,$44,$85
@ref184:
	.byte $41,$45,$49,$4b,$4f,$4d,$4f,$49,$4b,$4f,$53,$55,$59,$57,$59,$52
	.byte $81
@ref185:
	.byte $9c,$55,$5d,$4f,$55,$49,$4f,$41,$49,$4b,$53,$41,$4b,$3b,$41,$33
	.byte $3a,$81
@ref186:
	.byte $8e,$41,$45,$49,$4b,$4f,$4d,$4f,$49,$4b,$4f,$53,$55,$59,$57,$59
	.byte $52,$81
@ref187:
	.byte $9c,$59,$61,$53,$59,$49,$53,$41,$49,$49,$51,$57,$61,$53,$01,$53
	.byte $00,$81
	.byte $fd
	.word @song1ch1loop

@song1ch2:
@song1ch2loop:
@ref188:
	.byte $a0,$30,$85,$26,$85,$30,$85,$28,$85
@ref189:
	.byte $30,$85,$39,$3f,$49,$01,$30,$85
@ref190:
	.byte $3b,$48,$00,$41,$48,$00,$3b,$48,$00,$41,$48,$00,$3b,$4a,$00,$45
	.byte $4a,$00,$3b,$48,$00,$41,$48,$00
@ref191:
	.byte $45,$3a,$00,$45,$3a,$00,$49,$3a,$00,$49,$3a,$00,$39,$3e,$00,$31
	.byte $3e,$00,$3b,$30,$00,$3b,$00,$81
	.byte $ff,$18
	.word @ref190
@ref193:
	.byte $3f,$4e,$00,$49,$4e,$00,$3f,$4e,$00,$49,$4e,$00,$3f,$46,$00,$4d
	.byte $46,$00,$49,$01,$30,$85
@ref194:
	.byte $3b,$40,$00,$49,$40,$00,$3b,$40,$00,$49,$40,$00,$45,$4a,$00,$53
	.byte $4a,$00,$45,$4a,$00,$53,$4a,$00
@ref195:
	.byte $31,$3e,$00,$31,$3e,$00,$31,$00,$89,$3b,$48,$00,$3b,$48,$00,$3b
	.byte $00,$89
	.byte $ff,$18
	.word @ref194
@ref197:
	.byte $31,$3a,$00,$31,$3a,$00,$31,$3a,$00,$31,$3a,$00,$31,$38,$00,$31
	.byte $38,$00,$3b,$00,$89
	.byte $ff,$18
	.word @ref190
	.byte $ff,$18
	.word @ref191
	.byte $ff,$18
	.word @ref190
	.byte $ff,$16
	.word @ref193
	.byte $ff,$18
	.word @ref194
	.byte $ff,$12
	.word @ref195
	.byte $ff,$18
	.word @ref194
	.byte $ff,$15
	.word @ref197
@ref206:
	.byte $40,$85,$3e,$85,$3c,$85,$3a,$85
@ref207:
	.byte $36,$85,$32,$85,$30,$85,$2c,$85
@ref208:
	.byte $37,$01,$41,$01,$37,$01,$41,$37,$33,$01,$41,$01,$33,$01,$41,$3a
	.byte $81
	.byte $ff,$11
	.word @ref208
@ref210:
	.byte $37,$01,$41,$01,$37,$01,$41,$37,$33,$01,$41,$01,$33,$01,$41,$32
	.byte $81
@ref211:
	.byte $3b,$01,$49,$01,$3b,$01,$49,$41,$31,$01,$3f,$01,$3b,$01,$3b,$00
	.byte $81
	.byte $fd
	.word @song1ch2loop

@song1ch3:
@song1ch3loop:
@ref212:
	.byte $8c,$0c,$85,$8a,$11,$8c,$0d,$0c,$85,$8a,$11,$8c,$0c,$81
@ref213:
	.byte $0d,$8a,$11,$8c,$0d,$8a,$11,$8c,$0c,$85,$88,$11,$10,$10
@ref214:
	.byte $05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0f,$88
	.byte $05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0e,$81
@ref215:
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0f
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$8c,$09,$8a,$0f,$8c,$09,$08,$81
@ref216:
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0f
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0e
	.byte $81
	.byte $ff,$11
	.word @ref215
@ref218:
	.byte $11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c
	.byte $11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$10,$81
@ref219:
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$8c,$14,$85,$15,$8a,$15,$88,$05
	.byte $8a,$0f,$8c,$05,$8a,$0f,$8c,$14,$85,$15,$8a,$14,$81
@ref220:
	.byte $8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11
	.byte $8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$11,$8c,$11,$8a,$10
	.byte $81
@ref221:
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$88,$05,$8a,$0f,$8c,$05,$8a,$0f
	.byte $88,$05,$8a,$0f,$8c,$05,$8a,$0f,$8c,$14,$85,$15,$8a,$14,$81
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref215
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref215
	.byte $ff,$11
	.word @ref218
	.byte $ff,$11
	.word @ref219
	.byte $ff,$11
	.word @ref220
	.byte $ff,$11
	.word @ref221
@ref230:
	.byte $8c,$0f,$8a,$0f,$8c,$0f,$8a,$0f,$8c,$0f,$8a,$0f,$8c,$0f,$8a,$0e
	.byte $81
@ref231:
	.byte $8c,$0f,$8a,$0f,$8c,$0f,$8a,$0f,$8c,$0f,$8a,$0f,$8c,$19,$18,$18
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref216
	.byte $ff,$11
	.word @ref216
	.byte $fd
	.word @song1ch3loop

@song1ch4:
@song1ch4loop:
@ref236:
	.byte $9f
@ref237:
	.byte $9f
@ref238:
	.byte $bf
@ref239:
	.byte $bf
@ref240:
	.byte $bf
@ref241:
	.byte $bf
@ref242:
	.byte $bf
@ref243:
	.byte $bf
@ref244:
	.byte $bf
@ref245:
	.byte $bf
@ref246:
	.byte $bf
@ref247:
	.byte $bf
@ref248:
	.byte $bf
@ref249:
	.byte $bf
@ref250:
	.byte $bf
@ref251:
	.byte $bf
@ref252:
	.byte $bf
@ref253:
	.byte $bf
@ref254:
	.byte $9f
@ref255:
	.byte $9f
@ref256:
	.byte $bf
@ref257:
	.byte $bf
@ref258:
	.byte $bf
@ref259:
	.byte $bf
	.byte $fd
	.word @song1ch4loop


@song2ch0:
	.byte $fb,$06
@ref260:
	.byte $94,$63,$58,$51,$4a,$47,$40,$83,$00,$41,$46,$01,$4a,$00,$b9
@song2ch0loop:
@ref261:
	.byte $81
	.byte $fd
	.word @song2ch0loop

@song2ch1:
@ref262:
	.byte $94,$59,$50,$4b,$40,$3d,$36,$83,$00,$39,$40,$01,$40,$00,$b9
@song2ch1loop:
@ref263:
	.byte $81
	.byte $fd
	.word @song2ch1loop

@song2ch2:
@ref264:
	.byte $a0,$32,$85,$00,$32,$83,$00,$32,$83,$29,$00,$29,$32,$00,$b9
@song2ch2loop:
@ref265:
	.byte $81
	.byte $fd
	.word @song2ch2loop

@song2ch3:
@ref266:
	.byte $8c,$05,$88,$0e,$0f,$8c,$04,$83,$88,$0a,$8c,$05,$88,$0a,$0b,$8c
	.byte $04,$83,$88,$0a,$8c,$04,$b9
@song2ch3loop:
@ref267:
	.byte $81
	.byte $fd
	.word @song2ch3loop

@song2ch4:
@ref268:
	.byte $df
@song2ch4loop:
@ref269:
	.byte $81
	.byte $fd
	.word @song2ch4loop


@song3ch0:
	.byte $fb,$06
@ref270:
	.byte $9c,$5c,$85,$5d,$61,$5d,$61,$64,$8f,$00,$f9,$99
@song3ch0loop:
@ref271:
	.byte $81
	.byte $fd
	.word @song3ch0loop

@song3ch1:
@ref272:
	.byte $9c,$52,$85,$53,$57,$53,$57,$5c,$8f,$00,$f9,$99
@song3ch1loop:
@ref273:
	.byte $81
	.byte $fd
	.word @song3ch1loop

@song3ch2:
@ref274:
	.byte $a0,$2d,$3b,$45,$31,$3f,$49,$2c,$8f,$00,$f9,$99
@song3ch2loop:
@ref275:
	.byte $81
	.byte $fd
	.word @song3ch2loop

@song3ch3:
@ref276:
	.byte $8c,$0b,$88,$0a,$0a,$0b,$8c,$0b,$0b,$0b,$0a,$f9,$ab
@song3ch3loop:
@ref277:
	.byte $81
	.byte $fd
	.word @song3ch3loop

@song3ch4:
@ref278:
	.byte $f9,$c5
@song3ch4loop:
@ref279:
	.byte $81
	.byte $fd
	.word @song3ch4loop


@song4ch0:
	.byte $fb,$08
@song4ch0loop:
@ref280:
	.byte $84,$60,$83,$60,$83,$58,$87,$58,$5d,$4e,$52,$83,$4e,$89
@ref281:
	.byte $60,$83,$60,$83,$61,$52,$59,$5c,$85,$00,$8f
@ref282:
	.byte $60,$83,$60,$83,$58,$87,$58,$5d,$4e,$52,$83,$4e,$87,$5c
@ref283:
	.byte $60,$83,$60,$83,$5d,$58,$5d,$59,$00,$80,$5c,$85,$58,$89
	.byte $ff,$0d
	.word @ref280
	.byte $ff,$0b
	.word @ref281
	.byte $ff,$0e
	.word @ref282
	.byte $ff,$0d
	.word @ref283
@ref288:
	.byte $83,$96,$52,$59,$52,$59,$52,$00,$00,$58,$5d,$60,$01,$5c,$01,$58
	.byte $83,$60
@ref289:
	.byte $5d,$58,$52,$00,$60,$5d,$58,$52,$00,$58,$5c,$00,$85,$80,$5c,$83
	.byte $5c,$85
@ref290:
	.byte $58,$83,$96,$53,$4e,$83,$52,$85,$80,$5d,$96,$58,$5d,$58,$01,$58
	.byte $5d,$58
@ref291:
	.byte $5d,$00,$83,$58,$5d,$00,$83,$60,$5d,$60,$01,$5c,$01,$59,$00,$84
	.byte $5c
	.byte $fd
	.word @song4ch0loop

@song4ch1:
@song4ch1loop:
@ref292:
	.byte $86,$28,$83,$37,$40,$29,$36,$41,$36,$1e,$83,$2d,$36,$1f,$2c,$37
	.byte $2c
@ref293:
	.byte $28,$83,$37,$40,$29,$36,$41,$36,$1e,$83,$2d,$36,$1f,$2c,$37,$2c
	.byte $ff,$10
	.word @ref293
@ref295:
	.byte $22,$83,$31,$3a,$27,$32,$3f,$41,$00,$80,$52,$85,$4e,$89
	.byte $ff,$10
	.word @ref292
	.byte $ff,$10
	.word @ref293
	.byte $ff,$10
	.word @ref293
	.byte $ff,$0d
	.word @ref295
@ref300:
	.byte $90,$3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$36,$3e,$44
	.byte $36,$3e,$44,$36,$3e,$44,$36,$3e,$44
@ref301:
	.byte $3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$3e,$44,$4e,$3e
	.byte $44,$4e,$3e,$44,$4e,$3e,$44,$4e
@ref302:
	.byte $3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$36,$3e,$44,$36
	.byte $3e,$44,$36,$3e,$44,$36,$3e,$44
@ref303:
	.byte $3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$3a,$40,$4a,$96,$57,$58,$01
	.byte $52,$01,$4f,$00,$81
	.byte $fd
	.word @song4ch1loop

@song4ch2:
@song4ch2loop:
@ref304:
	.byte $a0,$29,$00,$41,$00,$28,$00,$28,$40,$83,$1f,$00,$37,$00,$1e,$00
	.byte $1e,$36,$83
@ref305:
	.byte $29,$00,$41,$00,$28,$00,$28,$40,$83,$1f,$00,$37,$00,$1e,$00,$1e
	.byte $36,$83
	.byte $ff,$12
	.word @ref305
@ref307:
	.byte $23,$00,$3b,$00,$26,$00,$26,$3f,$29,$00,$41,$01,$29,$00,$85
	.byte $ff,$12
	.word @ref305
	.byte $ff,$12
	.word @ref305
	.byte $ff,$12
	.word @ref305
@ref311:
	.byte $23,$00,$3b,$00,$26,$00,$26,$3f,$29,$00,$41,$01,$29,$00,$29,$22
@ref312:
	.byte $1b,$32,$01,$32,$01,$32,$01,$32,$1f,$36,$01,$36,$01,$36,$01,$36
	.byte $ff,$10
	.word @ref312
	.byte $ff,$10
	.word @ref312
	.byte $ff,$10
	.word @ref312
	.byte $fd
	.word @song4ch2loop

@song4ch3:
@song4ch3loop:
@ref316:
	.byte $88,$0f,$0e,$8c,$0b,$0a,$88,$0f,$0e,$8c,$0a,$83,$88,$0f,$0e,$8c
	.byte $0b,$0a,$88,$0f,$0e,$8c,$0a,$83
	.byte $ff,$10
	.word @ref316
	.byte $ff,$10
	.word @ref316
@ref319:
	.byte $88,$0f,$0e,$8c,$0b,$0a,$0d,$88,$0e,$8c,$0b,$18,$83,$0c,$85,$0c
	.byte $83,$0d,$0c
	.byte $ff,$10
	.word @ref316
	.byte $ff,$10
	.word @ref316
	.byte $ff,$10
	.word @ref316
	.byte $ff,$0f
	.word @ref319
	.byte $ff,$10
	.word @ref316
	.byte $ff,$10
	.word @ref316
	.byte $ff,$10
	.word @ref316
@ref327:
	.byte $88,$0f,$0e,$8c,$0b,$0a,$88,$0f,$0e,$8c,$0a,$83,$09,$08,$83,$08
	.byte $83,$08,$83,$08
	.byte $fd
	.word @song4ch3loop

@song4ch4:
@song4ch4loop:
@ref328:
	.byte $af
@ref329:
	.byte $af
@ref330:
	.byte $af
@ref331:
	.byte $af
@ref332:
	.byte $af
@ref333:
	.byte $af
@ref334:
	.byte $af
@ref335:
	.byte $af
@ref336:
	.byte $af
@ref337:
	.byte $af
@ref338:
	.byte $af
@ref339:
	.byte $af
	.byte $fd
	.word @song4ch4loop


@song5ch0:
	.byte $fb,$07
@song5ch0loop:
@ref340:
	.byte $86,$36,$01,$36,$01,$2c,$00,$8b,$28,$01,$28,$2c,$01,$2c,$00,$81
@ref341:
	.byte $36,$01,$36,$01,$2c,$00,$8b,$28,$01,$28,$2c,$01,$2c,$00,$81
	.byte $ff,$0f
	.word @ref341
	.byte $ff,$0f
	.word @ref341
	.byte $ff,$0f
	.word @ref341
	.byte $ff,$0f
	.word @ref341
@ref346:
	.byte $34,$01,$2c,$01,$34,$00,$8b,$34,$01,$2c,$34,$01,$2c,$83
@ref347:
	.byte $30,$01,$28,$01,$30,$00,$8b,$30,$01,$28,$30,$01,$28,$83
	.byte $ff,$0e
	.word @ref346
@ref349:
	.byte $9c,$49,$00,$83,$44,$49,$00,$83,$4c,$48,$83,$00,$8f
	.byte $fd
	.word @song5ch0loop

@song5ch1:
@song5ch1loop:
@ref350:
	.byte $86,$3e,$01,$3e,$01,$36,$00,$8b,$30,$01,$30,$34,$01,$34,$00,$81
@ref351:
	.byte $3e,$01,$3e,$01,$36,$00,$8b,$30,$01,$30,$34,$01,$34,$00,$81
@ref352:
	.byte $3e,$01,$9c,$53,$4e,$53,$4e,$00,$87,$86,$30,$01,$30,$34,$01,$34
	.byte $00,$81
@ref353:
	.byte $3e,$01,$9c,$57,$52,$57,$5c,$01,$58,$01,$56,$01,$52,$83,$48,$4e
	.byte $00,$81
@ref354:
	.byte $86,$3e,$01,$9c,$53,$4e,$53,$4e,$00,$87,$86,$30,$01,$30,$34,$01
	.byte $34,$00,$81
	.byte $ff,$11
	.word @ref353
@ref356:
	.byte $86,$3e,$01,$9c,$57,$52,$57,$52,$01,$56,$01,$5c,$01,$56,$83,$5c
	.byte $57,$4e
@ref357:
	.byte $53,$4e,$52,$01,$53,$56,$01,$52,$01,$86,$3a,$01,$30,$3a,$01,$30
	.byte $83
@ref358:
	.byte $3e,$01,$9c,$57,$52,$57,$52,$01,$56,$01,$5c,$01,$56,$83,$5c,$57
	.byte $4e
@ref359:
	.byte $53,$00,$83,$4e,$53,$00,$83,$56,$52,$83,$00,$8f
	.byte $fd
	.word @song5ch1loop

@song5ch2:
@song5ch2loop:
@ref360:
	.byte $a0,$36,$83,$4e,$01,$30,$83,$48,$01,$28,$83,$40,$01,$2c,$83,$44
	.byte $00,$81
@ref361:
	.byte $36,$83,$4e,$01,$30,$83,$48,$01,$28,$83,$40,$01,$2c,$83,$44,$00
	.byte $81
	.byte $ff,$11
	.word @ref361
	.byte $ff,$11
	.word @ref361
	.byte $ff,$11
	.word @ref361
	.byte $ff,$11
	.word @ref361
@ref366:
	.byte $26,$83,$3e,$01,$26,$83,$3e,$01,$26,$83,$3e,$01,$26,$83,$3e,$00
	.byte $81
@ref367:
	.byte $22,$83,$3a,$01,$22,$83,$3a,$01,$22,$83,$3a,$01,$22,$83,$3a,$00
	.byte $81
	.byte $ff,$11
	.word @ref366
@ref369:
	.byte $22,$83,$3a,$01,$22,$83,$3a,$01,$22,$83,$00,$83,$2c,$01,$34,$00
	.byte $81
	.byte $fd
	.word @song5ch2loop

@song5ch3:
@song5ch3loop:
@ref370:
	.byte $88,$04,$83,$05,$04,$8a,$05,$88,$04,$05,$04,$83,$04,$83,$04,$8a
	.byte $05,$88,$04,$04,$83
@ref371:
	.byte $04,$83,$05,$04,$8a,$05,$88,$04,$05,$04,$83,$04,$83,$04,$8a,$05
	.byte $88,$04,$04,$83
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
	.byte $ff,$10
	.word @ref371
@ref379:
	.byte $8c,$14,$83,$88,$05,$04,$8c,$15,$88,$04,$05,$04,$8c,$14,$89,$14
	.byte $83,$15,$14
	.byte $fd
	.word @song5ch3loop

@song5ch4:
@song5ch4loop:
@ref380:
	.byte $af
@ref381:
	.byte $af
@ref382:
	.byte $af
@ref383:
	.byte $af
@ref384:
	.byte $af
@ref385:
	.byte $af
@ref386:
	.byte $af
@ref387:
	.byte $af
@ref388:
	.byte $af
@ref389:
	.byte $af
	.byte $fd
	.word @song5ch4loop


@song6ch0:
	.byte $fb,$07
@ref390:
	.byte $98,$45,$4a,$81
@song6ch0loop:
@ref391:
	.byte $98,$54,$55,$54,$55,$54,$81
@ref392:
	.byte $4f,$4b,$45,$4a,$81
@ref393:
	.byte $54,$89,$00,$81
@ref394:
	.byte $87,$55,$58,$81
@ref395:
	.byte $5c,$5d,$5c,$5d,$5c,$81
@ref396:
	.byte $63,$5d,$59,$54,$81
@ref397:
	.byte $58,$89,$00,$81
@ref398:
	.byte $87,$63,$5e,$81
	.byte $ff,$06
	.word @ref395
@ref400:
	.byte $59,$55,$4f,$4a,$81
@ref401:
	.byte $46,$47,$46,$47,$46,$81
@ref402:
	.byte $59,$55,$53,$4e,$81
@ref403:
	.byte $4a,$4b,$4a,$4b,$4a,$81
@ref404:
	.byte $5f,$5d,$4f,$52,$81
@ref405:
	.byte $54,$8d
@ref406:
	.byte $00,$85,$45,$4a,$81
	.byte $fd
	.word @song6ch0loop

@song6ch1:
@ref407:
	.byte $87
@song6ch1loop:
@ref408:
	.byte $84,$24,$2c,$32,$2c,$32,$3c,$24,$2c
@ref409:
	.byte $24,$2c,$32,$2c,$32,$3c,$24,$2c
	.byte $ff,$08
	.word @ref409
	.byte $ff,$08
	.word @ref409
@ref412:
	.byte $2c,$32,$3a,$32,$3a,$44,$2c,$32
	.byte $ff,$08
	.word @ref412
@ref414:
	.byte $28,$2e,$36,$2e,$36,$40,$28,$2e
	.byte $ff,$08
	.word @ref414
	.byte $ff,$08
	.word @ref409
	.byte $ff,$08
	.word @ref409
@ref418:
	.byte $1e,$24,$2e,$24,$2e,$36,$1e,$24
	.byte $ff,$08
	.word @ref418
@ref420:
	.byte $1a,$22,$28,$22,$28,$32,$1a,$22
	.byte $ff,$08
	.word @ref420
	.byte $ff,$08
	.word @ref409
@ref423:
	.byte $25,$00,$89
	.byte $fd
	.word @song6ch1loop

@song6ch2:
@ref424:
	.byte $87
@song6ch2loop:
@ref425:
	.byte $a0,$25,$32,$00,$3d,$32,$00
@ref426:
	.byte $25,$2c,$32,$3d,$32,$00
@ref427:
	.byte $25,$32,$00,$3d,$32,$00
	.byte $ff,$06
	.word @ref426
@ref429:
	.byte $2d,$3a,$00,$45,$3a,$00
@ref430:
	.byte $2d,$32,$3a,$45,$3a,$00
@ref431:
	.byte $29,$36,$00,$41,$36,$00
@ref432:
	.byte $29,$2e,$36,$41,$36,$00
	.byte $ff,$06
	.word @ref427
	.byte $ff,$06
	.word @ref426
@ref435:
	.byte $2f,$3c,$00,$47,$3c,$00
@ref436:
	.byte $2f,$36,$3c,$47,$3c,$00
@ref437:
	.byte $29,$3a,$00,$41,$3a,$00
@ref438:
	.byte $29,$32,$3a,$41,$3a,$00
	.byte $ff,$06
	.word @ref427
@ref440:
	.byte $25,$00,$89
	.byte $fd
	.word @song6ch2loop

@song6ch3:
@ref441:
	.byte $87
@song6ch3loop:
@ref442:
	.byte $88,$1a,$1a,$8c,$09,$88,$10,$10,$8c,$08,$81
@ref443:
	.byte $88,$16,$16,$8c,$09,$88,$0c,$0c,$8c,$08,$81
@ref444:
	.byte $88,$1a,$1a,$8c,$09,$88,$10,$10,$10,$81
@ref445:
	.byte $16,$16,$8c,$09,$88,$10,$10,$8c,$08,$81
	.byte $ff,$07
	.word @ref442
@ref447:
	.byte $88,$16,$16,$8c,$09,$88,$10,$10,$8c,$08,$81
	.byte $ff,$07
	.word @ref442
	.byte $ff,$07
	.word @ref447
	.byte $ff,$07
	.word @ref442
	.byte $ff,$07
	.word @ref443
	.byte $ff,$07
	.word @ref444
	.byte $ff,$07
	.word @ref445
	.byte $ff,$07
	.word @ref442
	.byte $ff,$07
	.word @ref447
	.byte $ff,$07
	.word @ref442
@ref457:
	.byte $11,$00,$89
	.byte $fd
	.word @song6ch3loop

@song6ch4:
@ref458:
	.byte $87
@song6ch4loop:
@ref459:
	.byte $8f
@ref460:
	.byte $8f
@ref461:
	.byte $8f
@ref462:
	.byte $8f
@ref463:
	.byte $8f
@ref464:
	.byte $8f
@ref465:
	.byte $8f
@ref466:
	.byte $8f
@ref467:
	.byte $8f
@ref468:
	.byte $8f
@ref469:
	.byte $8f
@ref470:
	.byte $8f
@ref471:
	.byte $8f
@ref472:
	.byte $8f
@ref473:
	.byte $8f
@ref474:
	.byte $8f
	.byte $fd
	.word @song6ch4loop


@song7ch0:
	.byte $fb,$06
@song7ch0loop:
@ref475:
	.byte $94,$4a,$8d,$52,$85,$58,$89,$5d,$58,$85
@ref476:
	.byte $58,$8d,$52,$85,$4a,$8d,$52,$85
@ref477:
	.byte $54,$85,$52,$85,$4e,$85,$4a,$85,$48,$85,$4a,$85
@ref478:
	.byte $4e,$89,$53,$4a,$85,$48,$95
@ref479:
	.byte $4a,$8d,$52,$85,$58,$89,$5d,$58,$85
	.byte $ff,$08
	.word @ref476
@ref481:
	.byte $54,$85,$52,$85,$4e,$85,$4a,$85,$48,$85,$52,$85
@ref482:
	.byte $4e,$8d,$53,$4f,$4a,$95
	.byte $fd
	.word @song7ch0loop

@song7ch1:
@song7ch1loop:
@ref483:
	.byte $84,$33,$3b,$41,$3b,$41,$3a,$89,$41,$3b,$41,$3a,$81
@ref484:
	.byte $33,$3b,$41,$3b,$41,$3a,$89,$41,$3b,$41,$3a,$81
@ref485:
	.byte $33,$3d,$45,$3d,$45,$3c,$89,$41,$3b,$41,$3a,$81
@ref486:
	.byte $2d,$37,$3d,$37,$3d,$36,$89,$41,$37,$41,$36,$81
	.byte $ff,$0c
	.word @ref484
	.byte $ff,$0c
	.word @ref484
	.byte $ff,$0c
	.word @ref485
@ref490:
	.byte $31,$37,$41,$37,$41,$36,$89,$41,$3b,$41,$3a,$81
	.byte $fd
	.word @song7ch1loop

@song7ch2:
@song7ch2loop:
@ref491:
	.byte $a0,$1a,$95,$28,$95
@ref492:
	.byte $22,$95,$1a,$95
@ref493:
	.byte $24,$95,$22,$95
@ref494:
	.byte $1e,$95,$28,$95
@ref495:
	.byte $1a,$95,$28,$95
@ref496:
	.byte $22,$95,$1a,$95
@ref497:
	.byte $24,$95,$22,$95
@ref498:
	.byte $28,$95,$1a,$95
	.byte $fd
	.word @song7ch2loop

@song7ch3:
@song7ch3loop:
@ref499:
	.byte $af
@ref500:
	.byte $af
@ref501:
	.byte $af
@ref502:
	.byte $af
@ref503:
	.byte $af
@ref504:
	.byte $af
@ref505:
	.byte $af
@ref506:
	.byte $af
	.byte $fd
	.word @song7ch3loop

@song7ch4:
@song7ch4loop:
@ref507:
	.byte $af
@ref508:
	.byte $af
@ref509:
	.byte $af
@ref510:
	.byte $af
@ref511:
	.byte $af
@ref512:
	.byte $af
@ref513:
	.byte $af
@ref514:
	.byte $af
	.byte $fd
	.word @song7ch4loop
